### ISSUE TITLE
I just did a redis extension with redismodule-rs, made lots of changes along the way.

### ISSUE THREAD

**Issue by yihuang** [RedisLabsModules/redismodule-rs#11]
My redis extension: https://github.com/cryptorelay/redis-aggregation
My redismodule-rs fork: https://github.com/cryptorelay/redismodule-rs

There are lots of changes(probably breaking ones), if you want me to send a pull request anyway, I'm happy to.

**Comment by gkorland** [comment]
@yihuang thanks! please do send a PR it will be great if we can make a joint effort
