### ISSUE TITLE
Redis module command not persisted in the AOF file

### ISSUE THREAD

**Issue by mrzahrada** [RedisLabsModules/redismodule-rs#115]
Hi,
I'm trying to set up persistence for redis module with custom type. 
With 

```
127.0.0.1:6379> config get appendonly
1) "appendonly"
2) "yes"
```

default redis commands are persisted in AOF file but my custom commands are not written there. 
Is there anything I need to setup to make this work? Thank you

**Comment by MeirShpilraien** [comment]
@mrzahrada if you write your own module you need to use RM_Replicate/RM_ReplicateVerbatim to make sure your commands are replicated to replica and to AOF. Look at the documentation here:
https://redis.io/topics/modules-api-ref

**Comment by mrzahrada** [comment]
@MeirShpilraien Thank you, that solved my issue.
