### ISSUE TITLE
Accessing context within tests

### ISSUE THREAD

**Issue by naphta** [RedisLabsModules/redismodule-rs#135]
I may be being a little bit dense but I'm having a go at porting some lua scripts over to rust and I've got a barebone setup and I'm having trouble reading keys etc from within the tests as the context is null.

I can see that the source of the null context is `&Context::dummy(),` but I'm wondering what the alternative is here? Do I simply need to run my tests integration style and not actually in rust?

Is this intended or am I missing a step somewhere?

```

**Comment by gavrie** [comment]
@naphta the `dummy` context is there just to allow writing unit tests for the custom Redis commands defined in the examples. These tests run standalone and not inside Redis, so they can't access keys or anything.

For what you want to do, an integration test setup is indeed the way to go. You would want to use a Redis client (e.g. `redis-rs`) and run an actual Redis instance and load your module into it.

Not sure what you mean by "integration style and not actually in rust" -- such tests can of course be written in Rust or in any language you like (I have written such tests in Rust for some internally developed modules; one day we may add such tests to this project but don't hold your breath...). 
You can see an example of [Python based integration tests in RedisJSON](https://github.com/RedisJSON/RedisJSON/tree/master/tests/pytest), but those were written a while ago and I would write those in Rust if doing it from scratch.

**Comment by naphta** [comment]
I simply meant I don't have access to Rust native tests and would need to run integration tests (which are obviously testing the module, but don't need to be in Rust). Appreciate the decent reply though!

I'll take a look around at some testing strategies in Rust for bringing up fixtures (in this case Redis with a module loaded) for tests and if I get something which looks and feels good I'll do my best to get an example added to save other people my own confusion.

**Comment by gavrie** [comment]
@naphta I ported the integration tests that I mentioned to this module.
Please see #137.
