### ISSUE TITLE
Build on CentOS7 docker image fails with "'GLIBC_2.18' not found"

### ISSUE THREAD

**Issue by panpang** [RedisLabsModules/redismodule-rs#203]
OS is CentOS7 via docker image "image: centos:7"

the build is made using docker-compose via a .yaml file which has this image as its base:
`services:
    rpm_build-centos7:
        image: centos:7`

https://hub.docker.com/_/centos?tab=description
https://github.com/CentOS/sig-cloud-instance-images/blob/b2d195220e1c5b181427c3172829c23ab9cd27eb/docker/Dockerfile

the important section in the .yaml file that performs the build is this command sequence
```       command: bash -c "
            yum upgrade -y &&
            yum update -y &&
            
            yum install -y  glibc glibc-common glibc-devel wget curl gcc make clang clang-devel &&

            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | /bin/sh -s -- -y &&
            
            export PATH=/usr/local/cargo/bin:/usr/sbin:/usr/bin:/sbin:/bin &&

            cargo build --release &&
            
            cargo install cargo-generate-rpm &&
            cargo generate-rpm
            "
```
the project .toml has this dependency:
```
[dependencies]
redis-module = { version="0.23", features = ["experimental-api"] }
```

The "cargo build" fails with this last error:

```
rpm_build-centos7_1  |   Downloaded clang-sys v1.2.2
rpm_build-centos7_1  |   Downloaded libc v0.2.103
rpm_build-centos7_1  |  Downloading crates ...
rpm_build-centos7_1  |   Downloaded anyhow v1.0.44
rpm_build-centos7_1  |    Compiling redis-module v0.23.0
rpm_build-centos7_1  | error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /build/target/release/deps/libenum_primitive_derive-525852ee7a2d0d06.so)
rpm_build-centos7_1  |  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.23.0/src/raw.rs:5:1
rpm_build-centos7_1  |   |
rpm_build-centos7_1  | 5 | extern crate enum_primitive_derive;
rpm_build-centos7_1  |   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rpm_build-centos7_1  |
rpm_build-centos7_1  | error: could not compile `redis-module` due to previous error
local_rpm_build-centos7_1 exited with code 101
```
The error is
"error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /build/target/release/deps/libenum_primitive_derive-525852ee7a2d0d06.so)"

I checked around and there are a lot of result with confusing messages (to me) involving 
      Rust / GLIBC_2.18 / CentOS7
I could not find a solution to this. (note build is working fine on CentOS8, Ubuntu 20.04)
Does anyone know of this issue and hopefully a workaround?
We would very much like to support CentOS7 with our custom redis-module development

Thank you!

**Comment by panpang** [comment]
Tried to use build artifact built on CentOS8 on CentOS7, but naturally it does not work at runtime.
The build on CentOS-latest (CentOS8) produces a .so which contains this symbol (which is fine for CentOS8)

```
$ objdump -R libtc_redis_tools.so-centos-latest | grep GLIBC_2.18
000000000048d2d0 R_X86_64_GLOB_DAT  __cxa_thread_atexit_impl@GLIBC_2.18
```
This artifact built on CentOS8 does not work on redis on CentOS7 with error
```
redis-server --loadmodule xxx.so
```
```
Module xxx.so failed to load: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./xxx.so)
```

**Comment by chrisAtRedisLabs** [comment]
Would it be possible to post your docker-compose.yaml file?

**Comment by panpang** [comment]
Yes sure, thanks, 

please find it attached as "docker-rpm-build-centos7.yml.txt"
[docker-rpm-build-centos7.yml.txt](https://github.com/RedisLabsModules/redismodule-rs/files/7748771/docker-rpm-build-centos7.yml.txt)

also note that this file exists in a cargo project tree 
```
.
├── Cargo.lock
├── Cargo.toml
├── README.md
├── doc
│   ├── README-debrpm
│   ├── xxx
├── docker
│   ├── build
│   │   └── redis.conf
│   ├── docker-rpm-build-centos7.yml <-- HERE
│   ├── xxx
│   ├── readme.md
│   └── redis
│       ├── Dockerfile
│       ├── xx.so
│       └── redis.conf
├── dump_other.rdb
├── run-tests.sh
├── src
│   ├── bin
│   │   └── perftest.rs
├── start_other_redis.sh
├── target
└── tests
    ├── test-data
    │   └── readme.txt
    └── xxx.rs
```

and is called with
```
docker-compose -f docker-rpm-build-centos7.yml up
```

the project root is attached as a volume to the image in the "volumes" section

The project makes use of two types of features of the "redis_module!" macro
- custom commands
- init, deinit

**Comment by rafie** [comment]
Those who seek good fortune will invoke the following:
```
mkdir -p deps; cd deps; git clone https://github.com/RedisLabsModules/readies.git
```
and then proceed with their Docker build via Dockerfile (or alternatively, run `make platform OSNICK=centos7`).

The problem you're facing is due to the gcc version that's part of the CentOS 7 distribution. A newer version can installed, and this resolves the problem (you can look at `readies/bin/getgcc` for reference, and also examine our CircleCI build for CentOS 7 (e.g. https://app.circleci.com/pipelines/github/RedisLabsModules/redismodule-rs/678/workflows/8cc0ca00-8350-43be-ad7b-b759a034a1c0/jobs/1438).

**Comment by chrisAtRedisLabs** [comment]
It's unlikely that the above approach will work on aarch64 architectures as of some of the repos (such as remi) where the deps are pulled from apparently only support x864_64 for CentOS 7 versions.

**Comment by panpang** [comment]
thanks for the update. 
Tested on an image pulled from CentOS:7 and installing rpm 
http://rpms.remirepo.net/enterprise/7/remi/x86_64/redis-6.2.6-1.el7.remi.x86_64.rpm
and testing with "redis-server --loadmodule mymodule.so"
and the built module worked fine without any "`GLIBC_XXX not found" errors on stock CentOS:7 image.

Currently, there is no intention to deliver a solution for aarch64. 
Noted down that this won't work on aarch64 architectures.
thank you for the support.
