### ISSUE TITLE
The redis_module macro should follow some hygienic rules

### ISSUE THREAD

**Issue by Kerollmops** [RedisLabsModules/redismodule-rs#30]
I found out that it was an error to import `redismodule::raw` in the same scope where I call the `redis_module!` macro because the macro [already imported it](https://github.com/RedisLabsModules/redismodule-rs/blob/ca464e3814e0f289bc8ace02d012c1e1a61d727e/src/macros.rs#L72).

[So I read about how to import things](https://users.rust-lang.org/t/how-to-import-in-a-macro-without-conflicting/12785) in the scope of the function and avoid import conflicts in the user side, the conclusion is that for the `std` imports it would be better to use the full path everywhere and for the `redismodule` imports we should use `$crate`.

**Comment by gavrie** [comment]
@Kerollmops thanks for the input.
You're quite right; I will change this as you suggested.

**Comment by gavrie** [comment]
@Kerollmops I finally came around to fixing this. Better late than never...
