### ISSUE TITLE
Support firstkey, lastkey, and keystep in redis_module! and redis_command! macros

### ISSUE THREAD

**Issue by grippy** [RedisLabsModules/redismodule-rs#64]
These values are currently hardcoded to `1`. We should be able to configure these variables when calling the `redis_module!` macro.

**Comment by messense** [comment]
What does `firstkey, lastkey, and keystep` do? I can't find any docs about them.

**Comment by gavrie** [comment]
> What does `firstkey, lastkey, and keystep` do? I can't find any docs about them.

@messense You're quite right; the official Redis module API docs don't explain.
These parameters specify which of the arguments to the command are Redis keys: the index of the first argument that is a key, the last one, and the step (for commands like `MSET` that interleave keys and values).
