### ISSUE TITLE
Expose SubscribeToKeyspaceEvents

### ISSUE THREAD

**Issue by matobet** [RedisLabsModules/redismodule-rs#77]
It might be useful to expose in a rust-native way registration of event handlers to keyspace events (using the `RedisModule_SubscribeToKeyspaceEvents` API). E.g. a macro or such.

**Comment by matobet** [comment]
@gavrie could you please review https://github.com/RedisLabsModules/redismodule-rs/pull/78? it's been waiting for review for over a month.

**Comment by gavrie** [comment]
Fixed by #78
