### ISSUE TITLE
Curious, how production ready is this? Another question...

### ISSUE THREAD

**Issue by hiqbn** [RedisLabsModules/redismodule-rs#8]
Great work by the way.
1. how production ready is this?
2. redis is single threaded, rust is multiproc, so when ran, does that mean the rust part can do multiproc but overall, the app is still single threaded? the "bottleneck" will be at redis side but i think it's very minimal or not worth the consideration?

**Comment by gavrie** [comment]
@hiqbn thanks for the feedback!

1. It's a work in progress, not being used in production yet, but we hope to get there.
2. There is nothing in the code that creates threads or does any other kind of multiprocessing. It's certainly possible to write a module that creates threads, but than be done in C as well, nothing Rust-specific there.

**Comment by hiqbn** [comment]
just curious, when can we expect to see a production ready version 1.0?

**Comment by gavrie** [comment]
@hiqbn unfortunately I can't say that at the moment; we don't have a clear roadmap yet.

**Comment by hiqbn** [comment]
ok thx. will watch this repo. keep up the good work.
